/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programa;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author jjjav
 */
public class Menu extends javax.swing.JFrame {

    private boolean submenuabierto = false;

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Refresh.png")));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alzheimer.png")));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Notepad User.png")));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Albert Einstein.png")));

        btn_usermanual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User Manual.png")));

        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        btn_usermanual.addActionListener(this::btn_usermanualActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_convertir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btn_infoestudiante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_usermanual = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 93, 152));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(60, 141, 173));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjjav\\OneDrive\\Documentos\\NetBeansProjects\\Programa\\src\\main\\java\\com\\mycompany\\programa\\imagenes\\Refresh.png"));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        btn_convertir.setBackground(new java.awt.Color(181, 207, 221));
        btn_convertir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_convertir.setText("CONVERTIR");
        btn_convertir.setAlignmentY(0.0F);
        btn_convertir.setBorder(null);
        btn_convertir.setBorderPainted(false);
        btn_convertir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 30));

        jPanel2.setBackground(new java.awt.Color(60, 141, 173));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(60, 141, 173));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjjav\\OneDrive\\Documentos\\NetBeansProjects\\Programa\\src\\main\\java\\com\\mycompany\\programa\\imagenes\\Alzheimer.png"));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jComboBox1.setBackground(new java.awt.Color(181, 207, 221));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solución de problemas", "Suma de vectores", "Primera y tercera ley de Newton" }));
        jComboBox1.setToolTipText("Solución de problemas físicos");
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 200, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, -1));

        jPanel5.setBackground(new java.awt.Color(60, 141, 173));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_infoestudiante.setBackground(new java.awt.Color(181, 207, 221));
        btn_infoestudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_infoestudiante.setText("Información del estudiante");
        btn_infoestudiante.setBorder(null);
        btn_infoestudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_infoestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoestudianteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_infoestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjjav\\OneDrive\\Documentos\\NetBeansProjects\\Programa\\src\\main\\java\\com\\mycompany\\programa\\imagenes\\Notepad User.png"));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        jLabel5.setBackground(new java.awt.Color(245, 169, 98));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 169, 98));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Manual de Usuario");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 20));

        btn_usermanual.setBackground(new java.awt.Color(18, 93, 152));
        btn_usermanual.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjjav\\OneDrive\\Documentos\\NetBeansProjects\\Programa\\src\\main\\java\\com\\mycompany\\programa\\imagenes\\User Manual.png"));
        btn_usermanual.setBorder(null);
        btn_usermanual.setHideActionText(true);
        btn_usermanual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_usermanual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_usermanual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usermanualActionPerformed(evt);
            }
        });
        jPanel1.add(btn_usermanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu Inicial");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 340, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("con la experiencia.”");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 340, 20));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("conocimiento de las matemáticas.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 340, 20));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("en el laboratorio de física,");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 340, 20));

        jLabel9.setBackground(new java.awt.Color(245, 169, 98));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 169, 98));
        jLabel9.setText("Albert Einstein");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjjav\\OneDrive\\Documentos\\NetBeansProjects\\Programa\\src\\main\\java\\com\\mycompany\\programa\\imagenes\\Albert Einstein.png"));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 50, 40));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("“Hubiera podido lograr un profundo ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pero consumí la mayor parte del tiempo ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 340, 20));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("fascinado por el contacto directo");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 340, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertirActionPerformed
        Conversiones c = new Conversiones();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_convertirActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String opcionSeleccionada = jComboBox1.getSelectedItem().toString();

        if (opcionSeleccionada.equals("Suma de vectores") && !submenuabierto) {
            Sum_vectores s = new Sum_vectores();
            s.setVisible(true);
            submenuabierto = true;
            this.dispose();

        } else if (opcionSeleccionada.equals("Primera y tercera ley de Newton") && !submenuabierto) {
            LeyesNewton n = new LeyesNewton();
            n.setVisible(true);
            submenuabierto = true;
            this.dispose();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_infoestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoestudianteActionPerformed
        Info_estudiante i = new Info_estudiante();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_infoestudianteActionPerformed

    private void btn_usermanualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usermanualActionPerformed
        try (InputStream pdfStream = getClass().getResourceAsStream("/imagenes/Manual de usuario - Calculadora fisica.pdf")) {
            if (pdfStream == null) {
                JOptionPane.showMessageDialog(this, "El Archivo PDF no existe");
                return;
            }

            // Crear un archivo temporal para almacenar el PDF
            File tempFile = File.createTempFile("ManualUsuario", ".pdf");
            tempFile.deleteOnExit();

            try (OutputStream out = new FileOutputStream(tempFile)) {
                byte[] buffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = pdfStream.read(buffer)) != -1) {
                    out.write(buffer, 0, bytesRead);
                }
            }

            // Abrir el archivo PDF temporal
            Desktop.getDesktop().open(tempFile);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_usermanualActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convertir;
    private javax.swing.JButton btn_infoestudiante;
    private javax.swing.JButton btn_usermanual;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
